import { ArrowUpRight } from "lucide-react";
import data from "../../../data.json";
import SectionHeading from "../../components/SectionHeading";
const meta = {
  "unicsi-multi-tier-dropshipping-saas-platform": ["Multi-tenant commerce", "Disconnected supplier, store and fulfilment operations", "Centralized operations and improved traceability"],
  "owr-online-store-management-saas": ["Store management SaaS", "Commerce, logistics and billing spread across tools", "A unified tenant-aware operating system"],
  "dukkandaar-e-commerce-saas-platform": ["Web & mobile commerce", "Distinct admin, seller and buyer workflows", "Consistent role-based experiences across platforms"],
};
export default function Project() { return <section className="section-pad pt-0"><div className="site-container"><SectionHeading eyebrow="Selected work" title="Systems built around real business workflows." copy="A closer look at the product decisions, integrations and engineering behind each platform." /><div className="mt-14 divide-y divide-white/10 border-y border-white/10">{data.Projects.map((project,i) => { const [type,problem,outcome] = meta[project.slug]; return <article key={project.slug} className="group grid gap-7 py-9 md:grid-cols-[70px_1fr_1fr_auto] md:items-start md:gap-8"><p className="text-xs text-accent">0{i+1}</p><div><p className="text-[10px] uppercase tracking-[0.18em] text-white/35">{type}</p><h3 className="mt-3 text-2xl font-medium tracking-[-0.035em] sm:text-3xl">{project.title.split(" - ")[0]}</h3><p className="mt-2 text-sm text-white/40">{project.title.split(" - ")[1]}</p></div><dl className="space-y-4 text-sm"><div><dt className="text-[10px] uppercase tracking-[0.18em] text-white/30">The problem</dt><dd className="mt-1.5 leading-6 text-white/55">{problem}</dd></div><div><dt className="text-[10px] uppercase tracking-[0.18em] text-white/30">Outcome</dt><dd className="mt-1.5 leading-6 text-white/55">{outcome}</dd></div></dl><a href={`#/case-studies/${project.slug}`} className="grid h-12 w-12 place-items-center rounded-full border border-white/15 transition group-hover:border-accent group-hover:bg-accent group-hover:text-ink" aria-label={`Read ${project.title} case study`}><ArrowUpRight size={19} /></a></article>; })}</div></div></section>; }
