import { createElement } from "react";
import { ArrowUpRight, Bot, Code2, ShoppingBag, Waypoints } from "lucide-react";
import SectionHeading from "../../components/SectionHeading";
const services = [
  { icon: Code2, title: "Custom Software Development", copy: "Design and development of SaaS platforms, dashboards, internal tools and business applications tailored to specific operational requirements.", outcome: "Software shaped around your operation" },
  { icon: ShoppingBag, title: "Shopify Development", copy: "Custom Shopify storefronts, theme customization, Shopify APIs, integrations and purpose-built commerce functionality.", outcome: "A storefront connected to your business" },
  { icon: Waypoints, title: "E-commerce Systems", copy: "Connected systems for products, inventory, orders, fulfilment, payments, reporting and operational workflows.", outcome: "One reliable commerce workflow" },
  { icon: Bot, title: "Business Automation", copy: "Replace repetitive manual operations with APIs, integrations, automated workflows and focused internal tools.", outcome: "Less manual work, clearer operations" },
];
export default function Services() { return <section id="services" className="section-pad bg-surface"><div className="site-container"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="Services" title="How I can help your business." copy="Focused engineering support from the first workflow discussion through launch and iteration." /><a href="#contact" className="button button-secondary w-fit">Talk through a project <ArrowUpRight size={16} /></a></div><div className="mt-14 grid border-l border-t border-white/10 md:grid-cols-2">{services.map(({icon,title,copy,outcome},i) => <article key={title} className="group min-h-80 border-b border-r border-white/10 p-6 transition hover:bg-white/[0.025] sm:p-8"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-full border border-white/10 text-accent">{createElement(icon, { size: 19 })}</span><span className="text-xs text-white/25">0{i+1}</span></div><h3 className="mt-12 text-2xl font-medium tracking-[-0.03em]">{title}</h3><p className="mt-4 max-w-lg text-sm leading-7 text-white/45">{copy}</p><p className="mt-8 text-xs font-medium uppercase tracking-[0.14em] text-accent/80">{outcome}</p></article>)}</div></div></section>; }
